CREATE TABLE users (
    id UNIQUEIDENTIFIER NOT NULL,
    full_name NVARCHAR(160) NOT NULL,
    email NVARCHAR(80) NOT NULL,
    password_hash NVARCHAR(255) NOT NULL,
    created_at DATETIME2 NOT NULL,
    is_active BIT NOT NULL DEFAULT 0,
    role NVARCHAR(20) NOT NULL, 

    CONSTRAINT CHK_USER_ROLE CHECK (role in ('Worker', 'Analyst', 'Admin')),
    CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED (id),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
)GO

CREATE TABLE categories (
    id UNIQUEIDENTIFIER NOT NULL,
    name NVARCHAR(30) NOT NULL,
    description NVARCHAR(255) NULL,
    is_active BIT NOT NULL DEFAULT 1,

    CONSTRAINT PK_CATEGORY PRIMARY KEY CLUSTERED (id)
)GO

CREATE TABLE tickets (
    id UNIQUEIDENTIFIER NOT NULL,
    category_id UNIQUEIDENTIFIER NOT NULL,
    opened_by_user_id UNIQUEIDENTIFIER NOT NULL,
    assigned_to_user_id UNIQUEIDENTIFIER NULL,
    closed_by_user_id UNIQUEIDENTIFIER NULL,
    title NVARCHAR(80) NOT NULL,
    description NVARCHAR(255) NOT NULL,
    status NVARCHAR(20) NOT NULL,
    created_at DATETIME2 NOT NULL,
    updated_at DATETIME2 NOT NULL,
    closed_at DATETIME2 NULL, 

    CONSTRAINT PK_TICKETS_ID PRIMARY KEY CLUSTERED (id),
    CONSTRAINT CHK_TICKETS_STATUS CHECK (status in ('Open', 'InProgress', 'Closed')),
    CONSTRAINT FK_TICKETS_CATEGORIES FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT FK_TICKETS_OPENED_BY_USER FOREIGN KEY (opened_by_user_id) REFERENCES users(id),
    CONSTRAINT FK_TICKETS_ASSIGNED_TO_USER FOREIGN KEY (assigned_to_user_id) REFERENCES users(id)

)GO

CREATE TABLE ticket_interactions (
    id UNIQUEIDENTIFIER NOT NULL,
    ticket_id UNIQUEIDENTIFIER NOT NULL,
    user_id UNIQUEIDENTIFIER NOT NULL,
    message NVARCHAR(MAX) NOT NULL,
    created_at DATETIME2 NOT NULL,

    CONSTRAINT PK_TICKET_INTERACTIONS PRIMARY KEY CLUSTERED (id),
    CONSTRAINT FK_TICKET_TICKETINTERACTIONS FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    CONSTRAINT FK_USER_TICKETINTERACTIONS FOREIGN KEY (user_id) REFERENCES users(id)

    )GO

CREATE NONCLUSTERED INDEX IX_TICKETS_STATUS_CREATED_AT
ON tickets (status, created_at);
GO

CREATE NONCLUSTERED INDEX IX_TICKETS_ASSIGNED_TO_USER_STATUS
ON tickets (assigned_to_user_id, status);
GO

CREATE NONCLUSTERED INDEX IX_TICKETS_OPENED_BY_USER_CREATED_AT
ON tickets (opened_by_user_id, created_at);
GO

CREATE NONCLUSTERED INDEX IX_TICKETS_CATEGORY_STATUS
ON tickets (category_id, status);
GO

CREATE NONCLUSTERED INDEX IX_TICKET_INTERACTIONS_TICKET_ID_CREATED_AT
ON ticket_interactions (ticket_id, created_at);
GO

CREATE NONCLUSTERED INDEX IX_USERS_ROLE_IS_ACTIVE
ON users (role, is_active);
GO